# ds5-setup.ps1
# ===========================================================================
# DS5Dongle automation installer.
# Run this once (via ds5-setup.bat). It detects its own folder and generates
# all the automation scripts with the correct paths baked in, so you never edit
# a path by hand. Re-running is safe (it overwrites the generated files).
#
# It generates, next to itself:
#   ds5-global-start.ps1   ds5-global-stop.ps1
#   ds5-start.bat          ds5-stop.bat
#   native-games.txt       (only if missing - never overwrites your list)
#
# It expects these to already be present in the same folder:
#   ds5audio.py
#   profiles\audio-mix.autoapply.html
#   profiles\native-off.autoapply.html
#
# PowerShell 5.1-safe. Pure ASCII.
# ===========================================================================

# Base = the folder this installer lives in.
$Base = $PSScriptRoot
if (-not $Base) { $Base = Split-Path -Parent $MyInvocation.MyCommand.Definition }

Write-Host ""
Write-Host "DS5Dongle automation setup"
Write-Host "=========================="
Write-Host "Install folder: $Base"
Write-Host ""

# --- Sanity checks: warn (don't fail) if expected assets are missing. ---
$audioPy    = Join-Path $Base "ds5audio.py"
$profMix    = Join-Path $Base "profiles\audio-mix.autoapply.html"
$profNative = Join-Path $Base "profiles\native-off.autoapply.html"

function Check($path, $label) {
    if (Test-Path -LiteralPath $path) { Write-Host "  [OK]   $label" }
    else { Write-Host "  [WARN] missing: $label  ($path)" }
}
Check $audioPy    "ds5audio.py"
Check $profMix    "profiles\audio-mix.autoapply.html"
Check $profNative "profiles\native-off.autoapply.html"
Write-Host ""

# Helper to write a file from a here-string, substituting {{BASE}}.
function Write-Generated($name, $content) {
    $full = Join-Path $Base $name
    $out = $content.Replace("{{BASE}}", $Base)
    Set-Content -LiteralPath $full -Value $out -Encoding ASCII
    Write-Host "  wrote $name"
}

# ===========================================================================
# 1. ds5-global-start.ps1
# ===========================================================================
$startPs1 = @'
# ds5-global-start.ps1  (generated by ds5-setup - do not hand-edit)
# -ShowWindow : TEST MODE - launches ds5audio in a visible console that stays
#               open even if Python crashes, and mirrors log lines to screen.
param([string]$GameName = "", [switch]$ShowWindow, [switch]$GrantSetup)

# Self-detect our own folder so paths never go stale if the folder is moved.
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition }
$DS5Dir        = $scriptDir
$NativeList    = Join-Path $DS5Dir "native-games.txt"
$NativeProfile = Join-Path $DS5Dir "profiles\native-off.autoapply.html"
$AudioProfile  = Join-Path $DS5Dir "profiles\audio-mix.autoapply.html"
$AudioScript   = Join-Path $DS5Dir "ds5audio.py"
$AudioArgs     = @()   # e.g. @("--capture-name","SONY TV") to pin a capture device
$PythonExe     = ""    # OPTIONAL: full path to the python.exe that has PyAudioWPatch
                       # installed (the one that works when you run it manually).
                       # Leave "" to auto-detect from PATH.
$LogFile       = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -LiteralPath $LogFile -Value "$ts  [start] $m" -Encoding UTF8
    if ($ShowWindow) { Write-Host "[start] $m" }
}

$gameName = $GameName
if (-not $gameName) { try { if ($game -and $game.Name) { $gameName = [string]$game.Name } } catch { } }
# Fallback: Playnite's "before starting" event often does NOT expand {Name}, and the
# .bat runs outside Playnite's runtime (no $game). Read the launching game from
# Playnite's own log as a last resort.
if (-not $gameName) {
    $plog = Join-Path $env:APPDATA "Playnite\playnite.log"
    if (Test-Path -LiteralPath $plog) {
        try {
            $lines = Get-Content -LiteralPath $plog -Tail 200 -Encoding UTF8 -ErrorAction SilentlyContinue
            for ($i = $lines.Count - 1; $i -ge 0; $i--) {
                $mm = [regex]::Match($lines[$i], "(?:Starting|Started)\s+(.+?)(?:\s+game\b|\s*$)")
                if ($mm.Success -and $mm.Groups[1].Value.Trim()) { $gameName = $mm.Groups[1].Value.Trim().Trim('"').Trim("'"); Log "name from playnite.log: '$gameName'"; break }
            }
            if (-not $gameName) { Log "playnite.log tail (format diagnosis):"; foreach ($ln in ($lines | Select-Object -Last 6)) { Log "  | $ln" } }
        } catch { Log "playnite.log read failed: $($_.Exception.Message)" }
    } else { Log "playnite.log not found at $plog" }
}
Log "game: '$gameName'"

$isNative = $false
if (Test-Path -LiteralPath $NativeList) {
function Normalize-Name([string]$s) {
    # Fold to lowercase ASCII. This survives BOTH accented characters and
    # mojibake: 'Ragnar\u00f6k' sent as UTF-8 but decoded as ANSI arrives as
    # 'Ragnar\u00c3\u00b6k'; dropping every non-ASCII char makes both sides equal
    # ('ragnark'), so the native match works no matter which layer mangled it.
    if (-not $s) { return "" }
    (($s.ToLowerInvariant()).ToCharArray() | Where-Object { [int]$_ -ge 32 -and [int]$_ -le 126 }) -join ""
}
    # -Encoding UTF8 so accented list entries read correctly in PowerShell 5.1
    # (which otherwise assumes ANSI for BOM-less files).
    $needles = Get-Content -LiteralPath $NativeList -Encoding UTF8 -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
    $gnorm = Normalize-Name $gameName
    foreach ($n in $needles) {
        $nn = Normalize-Name $n
        $hit = if ($nn) { $gnorm.Contains($nn) }
               else { $gameName -and $gameName.ToLower().Contains($n.ToLower()) } # non-Latin entry: raw compare
        if ($hit) { $isNative = $true; Log "matched native entry: '$n'"; break }
    }
} else { Log "WARN native list not found: $NativeList" }

$global:DS5WasNative = $isNative

$BrowserExe      = "msedge"  # browser for profile pages, launched with --new-window
                             # so minimizing never touches your other tabs, and the
                             # page's self-close closes the whole window when done.
                             # Set "" to use the default handler (no minimize then).
$MinimizeBrowser = $true     # minimize the profile window right after it opens
$UseLocalServer  = $false    # keep $false: file:// is where existing grants live

function Resolve-Browser {
    if (-not $BrowserExe) { return $null }
    if (Test-Path -LiteralPath $BrowserExe) { return $BrowserExe }
    $c = Get-Command $BrowserExe -ErrorAction SilentlyContinue
    if ($c -and $c.Source) { return $c.Source }
    foreach ($g in @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
                     "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")) {
        if ($g -and (Test-Path -LiteralPath $g)) { return $g }
    }
    return $BrowserExe  # last resort: ShellExecute App Paths lookup
}

function Minimize-ProfileWindow([int]$timeoutMs = 6000) {
    # All profile pages carry the title "DS5 Bridge Config"; wait for that
    # window to appear, then minimize it. The page keeps full speed while
    # minimized (its HID waits run in a Web Worker, exempt from background
    # timer throttling) and closes its own window once the profile is saved.
    try {
        if (-not ("DS5.Win32" -as [type])) {
            Add-Type -Namespace DS5 -Name Win32 -MemberDefinition '[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);' -ErrorAction Stop
        }
    } catch { Log "WARN cannot load user32 for minimize: $($_.Exception.Message)"; return }
    $deadline = (Get-Date).AddMilliseconds($timeoutMs)
    while ((Get-Date) -lt $deadline) {
        $w = Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowHandle -ne [IntPtr]::Zero -and $_.MainWindowTitle -like "*DS5 Bridge Config*" } | Select-Object -First 1
        if ($w) { [DS5.Win32]::ShowWindowAsync($w.MainWindowHandle, 6) | Out-Null; Log "minimized profile window (PID $($w.Id))"; return } # 6 = SW_MINIMIZE
        Start-Sleep -Milliseconds 200
    }
    Log "note: profile window not seen to minimize (may have already self-closed)"
}

function Apply-Profile($htmlPath) {
    if (-not (Test-Path -LiteralPath $htmlPath)) { Log "WARN profile not found: $htmlPath"; return }
    try {
        # Open the html FILE directly (file:// origin). That is the origin your
        # browser's existing WebHID grant is stored against, and the launch
        # method that has always worked. $UseLocalServer = $true switches to
        # http://127.0.0.1:$ProfilePort serving instead (only useful if your
        # browser refuses to persist file:// grants; better: install the
        # policy via ds5-policy.bat, which covers both origins).
        $target = $htmlPath
        if ($UseLocalServer -and (Ensure-ProfileServer)) {
            $target = "http://127.0.0.1:$ProfilePort/" + [System.IO.Path]::GetFileName($htmlPath)
        }
        $b = Resolve-Browser
        if ($b) {
            Start-Process -FilePath $b -ArgumentList "--new-window", "`"$target`"" -ErrorAction Stop | Out-Null
        } else {
            $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $target; $psi.UseShellExecute = $true
            [System.Diagnostics.Process]::Start($psi) | Out-Null
        }
        Log "applied profile: $target"
        if ($b -and $MinimizeBrowser) { Minimize-ProfileWindow }
    } catch { Log "FAIL applying $htmlPath : $($_.Exception.Message)" }
}

# Build interpreter candidates in preference order. Do NOT exclude the
# Microsoft Store WindowsApps paths outright: when Python is installed FROM
# the Store, the real interpreter lives behind those exact paths. Non-Store
# paths are merely preferred; callers weed out fake alias stubs by checking
# whether the launched process actually does its job.
function Get-PythonCandidates {
    $pref  = @()
    $store = @()
    foreach ($name in @("pythonw", "python")) {
        foreach ($c in @(Get-Command $name -All -ErrorAction SilentlyContinue)) {
            if (-not $c.Source) { continue }
            if ($c.Source -like "*\Microsoft\WindowsApps\*") { $store += $c.Source }
            else { $pref += $c.Source }
        }
    }
    $out = @($pref) + @($store)
    # Last resort: the py launcher (installed by python.org installers
    # even when python itself is not on PATH).
    $pyl = Get-Command py -ErrorAction SilentlyContinue
    if ($pyl -and $pyl.Source) { $out += $pyl.Source }
    @($out | Select-Object -Unique)
}

$ProfilePort  = 8377
$ServerScript = Join-Path $DS5Dir "ds5-profile-server.py"

function Test-ProfileServer {
    try {
        $r = Invoke-WebRequest -Uri "http://127.0.0.1:$ProfilePort/__ds5" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        return ($r.Content -like "*ds5-profile-server*")
    } catch { return $false }
}

function Ensure-ProfileServer {
    if (Test-ProfileServer) { return $true }
    if (-not (Test-Path -LiteralPath $ServerScript)) { Log "WARN server script missing: $ServerScript"; return $false }
    foreach ($exe in @(Get-PythonCandidates)) {
        try {
            $argList = @()
            if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
            $argList += "`"$ServerScript`""
            Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -ErrorAction Stop | Out-Null
        } catch { continue }
        for ($i = 0; $i -lt 10; $i++) {
            Start-Sleep -Milliseconds 300
            if (Test-ProfileServer) { Log "profile server started via $exe"; return $true }
        }
    }
    Log "WARN could not start profile server (port $ProfilePort busy, or no working python)"
    return $false
}

if ($GrantSetup) {
    # Manual per-session grant fallback (run: ds5-global-start.ps1 -GrantSetup):
    # opens a profile page UNminimized so you can click "Connect & Apply".
    # Prefer ds5-policy.bat, which pre-grants permanently with no clicks.
    $MinimizeBrowser = $false
    Apply-Profile $AudioProfile
    Log "grant-setup: page opened; click Connect & Apply once if prompted"
    return
}

if ($isNative) {
    Apply-Profile $NativeProfile
    Log "native -> OFF profile, no capture"
} else {
    Apply-Profile $AudioProfile
    if (-not (Test-Path -LiteralPath $AudioScript)) {
        Log "WARN audio script not found: $AudioScript"
    } else {
        # Find running ds5audio processes. Get-CimInstance works in both Windows
        # PowerShell 5.1 and PowerShell 7 (Playnite's newer hosted runtime);
        # Get-WmiObject exists only in 5.1, so it is the fallback, not the default.
        function Get-DS5AudioProcs {
            $f = "Name='python.exe' OR Name='pythonw.exe'"
            $list = $null
            try { $list = Get-CimInstance -ClassName Win32_Process -Filter $f -ErrorAction Stop }
            catch { try { $list = Get-WmiObject -Class Win32_Process -Filter $f -ErrorAction Stop } catch { $list = @() } }
            @($list | Where-Object { $_.CommandLine -like "*ds5audio.py*" })
        }
        foreach ($p in (Get-DS5AudioProcs)) {
            try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; Log "stopped stray capture PID $($p.ProcessId)" } catch { }
        }
        # (Get-PythonCandidates is defined at top level - also used by the
        # profile server. Survival check below weeds out Store alias stubs.)
        $cands = @(Get-PythonCandidates)
        if ($PythonExe) {
            if (Test-Path -LiteralPath $PythonExe) { $cands = @($PythonExe); Log "using pinned PythonExe: $PythonExe" }
            else { Log "WARN pinned PythonExe not found ($PythonExe), falling back to auto-detect" }
        }
        if ($ShowWindow) {
            # Visible test mode needs a console interpreter, not pythonw.
            $vis = @($cands | Where-Object { (Split-Path -Leaf $_) -inotlike "pythonw*" })
            if ($vis.Count -gt 0) { $cands = $vis }
        }
        if ($cands.Count -eq 0) { Log "FAIL: no python/pythonw/py found on PATH" }
        else {
            Log ("python candidates: " + ($cands -join " | "))
            $started = $false
            foreach ($exe in $cands) {
                if ($started) { break }
                try {
                    $inner = ""
                    if ((Split-Path -Leaf $exe) -ieq "py.exe") { $inner = "-3 " }
                    $inner = "`"$exe`" $inner`"$AudioScript`""
                    foreach ($a in $AudioArgs) { $inner += " `"$a`"" }
                    if ($ShowWindow) {
                        # Run inside cmd /k so the window stays open even if
                        # Python exits/crashes instantly - you SEE the error.
                        $proc = Start-Process -FilePath "$env:ComSpec" -ArgumentList "/k `"$inner --verbose`"" -WorkingDirectory $DS5Dir -PassThru -ErrorAction Stop
                        Log "VISIBLE test launch via $exe (window stays open; close it to stop)"
                        $started = $true
                    } else {
                        $argList = @()
                        if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
                        $argList += "`"$AudioScript`""
                        $argList += $AudioArgs
                        $proc = Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -PassThru -ErrorAction Stop
                        Start-Sleep -Milliseconds 1500
                        if ($proc.HasExited) {
                            Log "WARN $exe exited immediately (code $($proc.ExitCode)) - Store stub or startup error (see ds5audio.log); trying next"
                        } else {
                            Log "ds5audio started (PID $($proc.Id) via $exe)"
                            $started = $true
                        }
                    }
                } catch { Log "FAIL starting via $exe : $($_.Exception.Message)" }
            }
            if (-not $started) { Log "FAIL: ds5audio did not stay running - check ds5audio.log in $DS5Dir" }
        }
    }
    Log "non-native -> mix profile + capture"
}
'@
Write-Generated "ds5-global-start.ps1" $startPs1

# ===========================================================================
# 2. ds5-global-stop.ps1
# ===========================================================================
$stopPs1 = @'
# ds5-global-stop.ps1  (generated by ds5-setup - do not hand-edit)
param([string]$GameName = "")

# Self-detect our own folder so paths never go stale if the folder is moved.
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition }
$DS5Dir       = $scriptDir
$NativeList   = Join-Path $DS5Dir "native-games.txt"
$AudioProfile = Join-Path $DS5Dir "profiles\audio-mix.autoapply.html"
$LogFile      = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) { $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"; Add-Content -LiteralPath $LogFile -Value "$ts  [stop]  $m" -Encoding UTF8 }

$wasNative = $false; $decided = $false
try { if ($null -ne $global:DS5WasNative) { $wasNative = [bool]$global:DS5WasNative; $decided = $true } } catch { }
if (-not $decided) {
    $gn = $GameName
    if (-not $gn) { try { if ($game -and $game.Name) { $gn = [string]$game.Name } } catch { } }
    if ($gn -and (Test-Path -LiteralPath $NativeList)) {
        function Normalize-Name([string]$s) {
            if (-not $s) { return "" }
            (($s.ToLowerInvariant()).ToCharArray() | Where-Object { [int]$_ -ge 32 -and [int]$_ -le 126 }) -join ""
        }
        $needles = Get-Content -LiteralPath $NativeList -Encoding UTF8 -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
        $gnorm = Normalize-Name $gn
        foreach ($n in $needles) {
            $nn = Normalize-Name $n
            $hit = if ($nn) { $gnorm.Contains($nn) } else { $gn.ToLower().Contains($n.ToLower()) }
            if ($hit) { $wasNative = $true; break }
        }
    }
    Log "game: '$gn' (re-checked list)"
}
Log "wasNative = $wasNative"

# Always stop any ds5audio (safety net).
# Get-CimInstance works in both Windows PowerShell 5.1 and PowerShell 7
# (Playnite's newer hosted runtime); Get-WmiObject exists only in 5.1, so it
# is the fallback. Stop-Process works in both.
function Get-DS5AudioProcs {
    $f = "Name='python.exe' OR Name='pythonw.exe'"
    $list = $null
    try { $list = Get-CimInstance -ClassName Win32_Process -Filter $f -ErrorAction Stop }
    catch { try { $list = Get-WmiObject -Class Win32_Process -Filter $f -ErrorAction Stop } catch { $list = @() } }
    @($list | Where-Object { $_.CommandLine -like "*ds5audio.py*" })
}
$n = 0
foreach ($p in (Get-DS5AudioProcs)) {
    try { Stop-Process -Id $p.ProcessId -Force -ErrorAction Stop; $n++; Log "stopped capture PID $($p.ProcessId)" }
    catch { Log "WARN could not stop PID $($p.ProcessId): $($_.Exception.Message)" }
}
Log "stopped $n audio capture process(es)"

if ($wasNative) {
    if (Test-Path -LiteralPath $AudioProfile) {
        $BrowserExe      = "msedge"  # keep in sync with ds5-global-start.ps1
        $MinimizeBrowser = $true
        $UseLocalServer  = $false    # keep in sync with ds5-global-start.ps1
        $ProfilePort     = 8377
        $ServerScript    = Join-Path $DS5Dir "ds5-profile-server.py"
        function Get-PythonCandidates {
            $pref = @(); $store = @()
            foreach ($name in @("pythonw", "python")) {
                foreach ($c in @(Get-Command $name -All -ErrorAction SilentlyContinue)) {
                    if (-not $c.Source) { continue }
                    if ($c.Source -like "*\Microsoft\WindowsApps\*") { $store += $c.Source } else { $pref += $c.Source }
                }
            }
            $out = @($pref) + @($store)
            $pyl = Get-Command py -ErrorAction SilentlyContinue
            if ($pyl -and $pyl.Source) { $out += $pyl.Source }
            @($out | Select-Object -Unique)
        }
        function Test-ProfileServer {
            try {
                $r = Invoke-WebRequest -Uri "http://127.0.0.1:$ProfilePort/__ds5" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
                return ($r.Content -like "*ds5-profile-server*")
            } catch { return $false }
        }
        function Ensure-ProfileServer {
            if (Test-ProfileServer) { return $true }
            if (-not (Test-Path -LiteralPath $ServerScript)) { return $false }
            foreach ($exe in @(Get-PythonCandidates)) {
                try {
                    $argList = @()
                    if ((Split-Path -Leaf $exe) -ieq "py.exe") { $argList += "-3" }
                    $argList += "`"$ServerScript`""
                    Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -ErrorAction Stop | Out-Null
                } catch { continue }
                for ($i = 0; $i -lt 10; $i++) {
                    Start-Sleep -Milliseconds 300
                    if (Test-ProfileServer) { Log "profile server started via $exe"; return $true }
                }
            }
            return $false
        }
        function Resolve-Browser {
            if (-not $BrowserExe) { return $null }
            if (Test-Path -LiteralPath $BrowserExe) { return $BrowserExe }
            $c = Get-Command $BrowserExe -ErrorAction SilentlyContinue
            if ($c -and $c.Source) { return $c.Source }
            foreach ($g in @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
                             "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe")) {
                if ($g -and (Test-Path -LiteralPath $g)) { return $g }
            }
            return $BrowserExe
        }
        function Minimize-ProfileWindow([int]$timeoutMs = 6000) {
            try {
                if (-not ("DS5.Win32" -as [type])) {
                    Add-Type -Namespace DS5 -Name Win32 -MemberDefinition '[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);' -ErrorAction Stop
                }
            } catch { return }
            $deadline = (Get-Date).AddMilliseconds($timeoutMs)
            while ((Get-Date) -lt $deadline) {
                $w = Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.MainWindowHandle -ne [IntPtr]::Zero -and $_.MainWindowTitle -like "*DS5 Bridge Config*" } | Select-Object -First 1
                if ($w) { [DS5.Win32]::ShowWindowAsync($w.MainWindowHandle, 6) | Out-Null; Log "minimized profile window (PID $($w.Id))"; return } # 6 = SW_MINIMIZE
                Start-Sleep -Milliseconds 200
            }
        }
        try {
            $target = $AudioProfile
            if ($UseLocalServer -and (Ensure-ProfileServer)) { $target = "http://127.0.0.1:$ProfilePort/" + [System.IO.Path]::GetFileName($AudioProfile) }
            $b = Resolve-Browser
            if ($b) { Start-Process -FilePath $b -ArgumentList "--new-window", "`"$target`"" -ErrorAction Stop | Out-Null }
            else {
                $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $target; $psi.UseShellExecute = $true
                [System.Diagnostics.Process]::Start($psi) | Out-Null
            }
            Log "native exited -> mix profile restored ($target)"
            if ($b -and $MinimizeBrowser) { Minimize-ProfileWindow }
        }
        catch { Log "FAIL applying mix profile: $($_.Exception.Message)" }
    } else { Log "WARN mix profile not found: $AudioProfile" }
} else { Log "non-native exited -> capture stopped" }
'@
Write-Generated "ds5-global-stop.ps1" $stopPs1

# ===========================================================================
# 3. ds5-start.bat and ds5-stop.bat
# ===========================================================================
$startBat = @'
@echo off
REM ds5-start.bat (generated) - Playnite "before starting a game" launcher.
REM In Playnite Settings -> Scripts, call it as:  "<folder>\ds5-start.bat" "{Name}"
REM chcp 65001 = UTF-8 so accented game names (e.g. the o-umlaut in Ragnarok) survive.
chcp 65001 >nul
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-start.ps1" -GameName "%~1"
'@
Write-Generated "ds5-start.bat" $startBat

$stopBat = @'
@echo off
REM ds5-stop.bat (generated) - Playnite "after exiting a game" launcher.
REM In Playnite Settings -> Scripts, call it as:  "<folder>\ds5-stop.bat" "{Name}"
chcp 65001 >nul
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-stop.ps1" -GameName "%~1"
'@
Write-Generated "ds5-stop.bat" $stopBat


# ===========================================================================
# 3b. Local profile server (opt-in, see $UseLocalServer) + policy grant bats
# ===========================================================================
$serverPy = @'
# ds5-profile-server.py (generated) - tiny loopback-only static server for the
# profile pages. Why it exists: WebHID device grants do NOT persist for
# file:// pages across browser restarts, so automated profile applies sat
# waiting for a manual "Connect" (unless a connected portal tab happened to be
# open). Grants for the http://127.0.0.1:8377 origin persist like a normal
# website; better yet, ds5-policy.bat pre-grants with no clicks at all. Covers
# forever. Binds 127.0.0.1 only - nothing is exposed to the network.
# Safe under pythonw: request logging is disabled (pythonw has no console).
import http.server
import socketserver
import os

PORT = 8377
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "profiles"))


class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args):  # no stdout/stderr under pythonw; stay silent
        pass

    def do_GET(self):
        if self.path == "/__ds5":  # health check used by the automation scripts
            body = b"ds5-profile-server"
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        return super().do_GET()


socketserver.TCPServer.allow_reuse_address = True
with socketserver.TCPServer(("127.0.0.1", PORT), Handler) as srv:
    srv.serve_forever()
'@
Write-Generated "ds5-profile-server.py" $serverPy

$policyBat = @'
@echo off
REM ds5-policy.bat (generated) - RECOMMENDED one-time setup. Writes the
REM Chromium policy "WebHidAllowDevicesForUrls" so the dongle (VID 054C,
REM PID 0CE6/0DF2) is PRE-GRANTED to the profile pages: no Connect click is
REM ever needed and nothing is lost when the browser closes or clears site
REM data. Side effect: Edge/Chrome show "Managed by your organization".
REM Fully reversible: run ds5-policy-remove.bat.
REM Requires admin (self-elevates). Restart the browser after running.

net session >nul 2>&1
if errorlevel 1 (
  echo Requesting administrator rights...
  powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b
)

set "POLICY=[{\"devices\":[{\"vendor_id\":1356,\"product_id\":3302},{\"vendor_id\":1356,\"product_id\":3570}],\"urls\":[\"file:///\",\"http://127.0.0.1:8377\"]}]"

reg add "HKLM\SOFTWARE\Policies\Microsoft\Edge"  /v WebHidAllowDevicesForUrls /t REG_SZ /d "%POLICY%" /f >nul
reg add "HKLM\SOFTWARE\Policies\Google\Chrome"   /v WebHidAllowDevicesForUrls /t REG_SZ /d "%POLICY%" /f >nul
echo.
echo Policy installed for Edge and Chrome.
echo Close ALL browser windows and reopen - profile pages then connect
echo silently, permanently. Verify at edge://policy if curious.
echo Undo anytime with ds5-policy-remove.bat.
pause
'@
Write-Generated "ds5-policy.bat" $policyBat

$policyRemoveBat = @'
@echo off
REM ds5-policy-remove.bat (generated) - undoes ds5-policy.bat completely:
REM deletes the WebHidAllowDevicesForUrls policy from Edge and Chrome.
REM Requires admin (self-elevates). Restart the browser afterwards; the
REM "Managed by your organization" notice disappears (unless other policies
REM exist on this machine).
net session >nul 2>&1
if errorlevel 1 (
  echo Requesting administrator rights...
  powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b
)
reg delete "HKLM\SOFTWARE\Policies\Microsoft\Edge" /v WebHidAllowDevicesForUrls /f >nul 2>&1
reg delete "HKLM\SOFTWARE\Policies\Google\Chrome"  /v WebHidAllowDevicesForUrls /f >nul 2>&1
echo Policy removed. Restart the browser.
pause
'@
Write-Generated "ds5-policy-remove.bat" $policyRemoveBat


# ===========================================================================
# 4. native-games.txt  (only if it doesn't already exist)
# ===========================================================================
$nativeList = Join-Path $Base "native-games.txt"
if (-not (Test-Path -LiteralPath $nativeList)) {
    $tpl = @'
# DS5 native-haptics games - one game name (or a distinctive part of it) per line.
# Matching is case-insensitive and partial: "Ratchet" matches "Ratchet & Clank: Rift Apart".
# Games listed here use native DualSense haptics (auto-haptics OFF, no ds5audio).
# Everything NOT listed uses the mix profile + ds5audio capture.
# Lines starting with # are ignored. Use a unique word to avoid false matches.
# For accented titles, use the plain-ASCII part before the accent (e.g. "Ragnar"
# for "God of War Ragnarok") so matching isn't affected by character encoding.
#
# Examples - replace with your own:
Ratchet
Returnal
Ragnar
Astro
'@
    Set-Content -LiteralPath $nativeList -Value $tpl -Encoding ASCII
    Write-Host "  wrote native-games.txt (template - edit it with your games)"
} else {
    Write-Host "  kept existing native-games.txt (not overwritten)"
}

# ===========================================================================
Write-Host ""
Write-Host "Done. In Playnite -> Settings -> Scripts, paste these into the SCRIPT boxes:"
Write-Host ""
Write-Host "  Executing before starting a game:"
Write-Host "    & `"$Base\ds5-start.bat`" `"{Name}`""
Write-Host ""
Write-Host "  Executing after exiting a game:"
Write-Host "    & `"$Base\ds5-stop.bat`" `"{Name}`""
Write-Host ""
Write-Host "One-time: run ds5-policy.bat (admin, self-elevates) so profile pages are"
Write-Host "pre-granted access to the dongle - no Connect clicks, survives restarts."
Write-Host "Reversible with ds5-policy-remove.bat."
Write-Host ""
Write-Host "Notes:"
Write-Host " - Use the .bat calls above with {Name}. If the log shows game: '' on start,"
Write-Host "   the start script falls back to reading Playnite's own log for the name."
Write-Host " - In native-games.txt, use a plain-ASCII fragment of the name (matching is"
Write-Host "   partial). For accented titles use the part before the accent, e.g. 'Ragnar'"
Write-Host "   for 'God of War Ragnarok'."
Write-Host " - Activity is logged to ds5-automation.log in this folder."
Write-Host ""
Read-Host "Press Enter to close"
