# ds5-setup.ps1
# ===========================================================================
# DS5Dongle automation installer.
# Run this once (via ds5-setup.bat). It detects its own folder and generates
# all the automation scripts with the correct paths baked in, so you never edit
# a path by hand. Re-running is safe (it overwrites the generated files).
#
# It generates, next to itself:
#   ds5-global-start.ps1   ds5-global-stop.ps1
#   ds5-start.bat          ds5-stop.bat
#   native-games.txt       (only if missing - never overwrites your list)
#
# It expects these to already be present in the same folder:
#   ds5audio.py
#   profiles\audio-mix.autoapply.html
#   profiles\native-off.autoapply.html
#
# PowerShell 5.1-safe. Pure ASCII.
# ===========================================================================

# Base = the folder this installer lives in.
$Base = $PSScriptRoot
if (-not $Base) { $Base = Split-Path -Parent $MyInvocation.MyCommand.Definition }

Write-Host ""
Write-Host "DS5Dongle automation setup"
Write-Host "=========================="
Write-Host "Install folder: $Base"
Write-Host ""

# --- Sanity checks: warn (don't fail) if expected assets are missing. ---
$audioPy    = Join-Path $Base "ds5audio.py"
$profMix    = Join-Path $Base "profiles\audio-mix.autoapply.html"
$profNative = Join-Path $Base "profiles\native-off.autoapply.html"

function Check($path, $label) {
    if (Test-Path -LiteralPath $path) { Write-Host "  [OK]   $label" }
    else { Write-Host "  [WARN] missing: $label  ($path)" }
}
Check $audioPy    "ds5audio.py"
Check $profMix    "profiles\audio-mix.autoapply.html"
Check $profNative "profiles\native-off.autoapply.html"
Write-Host ""

# Helper to write a file from a here-string, substituting {{BASE}}.
function Write-Generated($name, $content) {
    $full = Join-Path $Base $name
    $out = $content.Replace("{{BASE}}", $Base)
    Set-Content -LiteralPath $full -Value $out -Encoding ASCII
    Write-Host "  wrote $name"
}

# ===========================================================================
# 1. ds5-global-start.ps1
# ===========================================================================
$startPs1 = @'
# ds5-global-start.ps1  (generated by ds5-setup - do not hand-edit paths)
param([string]$GameName = "")

$DS5Dir        = "{{BASE}}"
$NativeList    = Join-Path $DS5Dir "native-games.txt"
$NativeProfile = Join-Path $DS5Dir "profiles\native-off.autoapply.html"
$AudioProfile  = Join-Path $DS5Dir "profiles\audio-mix.autoapply.html"
$AudioScript   = Join-Path $DS5Dir "ds5audio.py"
$AudioArgs     = @()   # e.g. @("--capture-name","SONY TV") to pin a capture device
$LogFile       = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) { $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"; Add-Content -LiteralPath $LogFile -Value "$ts  [start] $m" }

$gameName = $GameName
if (-not $gameName) { try { if ($game -and $game.Name) { $gameName = [string]$game.Name } } catch { } }
Log "game: '$gameName'"

$isNative = $false
if (Test-Path -LiteralPath $NativeList) {
    $needles = Get-Content -LiteralPath $NativeList -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
    foreach ($n in $needles) { if ($gameName -and $gameName.ToLower().Contains($n.ToLower())) { $isNative = $true; Log "matched native entry: '$n'"; break } }
} else { Log "WARN native list not found: $NativeList" }

$global:DS5WasNative = $isNative

function Apply-Profile($htmlPath) {
    if (Test-Path -LiteralPath $htmlPath) {
        try { $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $htmlPath; $psi.UseShellExecute = $true; [System.Diagnostics.Process]::Start($psi) | Out-Null; Log "applied profile: $htmlPath" }
        catch { Log "FAIL applying $htmlPath : $($_.Exception.Message)" }
    } else { Log "WARN profile not found: $htmlPath" }
}

if ($isNative) {
    Apply-Profile $NativeProfile
    Log "native -> OFF profile, no capture"
} else {
    Apply-Profile $AudioProfile
    if (-not (Test-Path -LiteralPath $AudioScript)) {
        Log "WARN audio script not found: $AudioScript"
    } else {
        $stray = Get-WmiObject -Class Win32_Process -Filter "Name='python.exe' OR Name='pythonw.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -like "*ds5audio.py*" }
        foreach ($p in $stray) { $p.Terminate() | Out-Null; Log "stopped stray capture PID $($p.ProcessId)" }
        $pyw = Get-Command pythonw -ErrorAction SilentlyContinue
        $py  = Get-Command python  -ErrorAction SilentlyContinue
        $exe = if ($pyw) { $pyw.Source } elseif ($py) { $py.Source } else { $null }
        if (-not $exe) { Log "FAIL: no python/pythonw on PATH" }
        else {
            try { $argList = @("`"$AudioScript`"") + $AudioArgs; $proc = Start-Process -FilePath $exe -ArgumentList $argList -WindowStyle Hidden -WorkingDirectory $DS5Dir -PassThru -ErrorAction Stop; Log "ds5audio started (PID $($proc.Id) via $exe)" }
            catch { Log "FAIL starting audio: $($_.Exception.Message)" }
        }
    }
    Log "non-native -> mix profile + capture"
}
'@
Write-Generated "ds5-global-start.ps1" $startPs1

# ===========================================================================
# 2. ds5-global-stop.ps1
# ===========================================================================
$stopPs1 = @'
# ds5-global-stop.ps1  (generated by ds5-setup - do not hand-edit paths)
param([string]$GameName = "")

$DS5Dir       = "{{BASE}}"
$NativeList   = Join-Path $DS5Dir "native-games.txt"
$AudioProfile = Join-Path $DS5Dir "profiles\audio-mix.autoapply.html"
$LogFile      = Join-Path $DS5Dir "ds5-automation.log"

function Log($m) { $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"; Add-Content -LiteralPath $LogFile -Value "$ts  [stop]  $m" }

$wasNative = $false; $decided = $false
try { if ($null -ne $global:DS5WasNative) { $wasNative = [bool]$global:DS5WasNative; $decided = $true } } catch { }
if (-not $decided) {
    $gn = $GameName
    if (-not $gn) { try { if ($game -and $game.Name) { $gn = [string]$game.Name } } catch { } }
    if ($gn -and (Test-Path -LiteralPath $NativeList)) {
        $needles = Get-Content -LiteralPath $NativeList -ErrorAction SilentlyContinue | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and -not $_.StartsWith("#") }
        foreach ($n in $needles) { if ($gn.ToLower().Contains($n.ToLower())) { $wasNative = $true; break } }
    }
    Log "game: '$gn' (re-checked list)"
}
Log "wasNative = $wasNative"

# Always stop any ds5audio (safety net).
$n = 0
$procs = Get-WmiObject -Class Win32_Process -Filter "Name='python.exe' OR Name='pythonw.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -like "*ds5audio.py*" }
foreach ($p in $procs) { $p.Terminate() | Out-Null; $n++ }
Log "stopped $n audio capture process(es)"

if ($wasNative) {
    if (Test-Path -LiteralPath $AudioProfile) {
        try { $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = $AudioProfile; $psi.UseShellExecute = $true; [System.Diagnostics.Process]::Start($psi) | Out-Null; Log "native exited -> mix profile restored" }
        catch { Log "FAIL applying mix profile: $($_.Exception.Message)" }
    } else { Log "WARN mix profile not found: $AudioProfile" }
} else { Log "non-native exited -> capture stopped" }
'@
Write-Generated "ds5-global-stop.ps1" $stopPs1

# ===========================================================================
# 3. ds5-start.bat and ds5-stop.bat
# ===========================================================================
$startBat = @'
@echo off
REM ds5-start.bat (generated) - Playnite "before starting a game".
REM Call in Playnite as:  "{{BASE}}\ds5-start.bat" "{Name}"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-start.ps1" -GameName "%~1"
'@
Write-Generated "ds5-start.bat" $startBat

$stopBat = @'
@echo off
REM ds5-stop.bat (generated) - Playnite "after exiting a game".
REM Call in Playnite as:  "{{BASE}}\ds5-stop.bat" "{Name}"
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0ds5-global-stop.ps1" -GameName "%~1"
'@
Write-Generated "ds5-stop.bat" $stopBat

# ===========================================================================
# 4. native-games.txt  (only if it doesn't already exist)
# ===========================================================================
$nativeList = Join-Path $Base "native-games.txt"
if (-not (Test-Path -LiteralPath $nativeList)) {
    $tpl = @'
# DS5 native-haptics games - one game name (or a distinctive part of it) per line.
# Matching is case-insensitive and partial: "Ratchet" matches "Ratchet & Clank: Rift Apart".
# Games listed here use native DualSense haptics (auto-haptics OFF, no ds5audio).
# Everything NOT listed uses the mix profile + ds5audio capture.
# Lines starting with # are ignored. Use a unique word to avoid false matches.
#
# Examples - replace with your own:
Ratchet
Returnal
Ragnarok
Astro
'@
    Set-Content -LiteralPath $nativeList -Value $tpl -Encoding ASCII
    Write-Host "  wrote native-games.txt (template - edit it with your games)"
} else {
    Write-Host "  kept existing native-games.txt (not overwritten)"
}

# ===========================================================================
Write-Host ""
Write-Host "Done. Now in Playnite -> Settings -> Scripts (or per game), set:"
Write-Host ""
Write-Host "  Before starting a game:"
Write-Host "    `"$Base\ds5-start.bat`" `"{Name}`""
Write-Host ""
Write-Host "  After exiting a game:"
Write-Host "    `"$Base\ds5-stop.bat`" `"{Name}`""
Write-Host ""
Write-Host "Edit native-games.txt to list your native-haptics games."
Write-Host "Activity is logged to ds5-automation.log in this folder."
Write-Host ""
Read-Host "Press Enter to close"
